---
name: cloudflared
version: 2026.1.1
slug: cloudflared
image: ghcr.io/chrisx8/hassio-cloudflared-{arch}
description: Cloudflare Tunnel client
url: https://github.com/chrisx8/hassio-addons/tree/main/cloudflared
startup: services
panel_icon: mdi:cloud
arch:
  - aarch64
  - amd64
init: false
options:
  token: ""
schema:
  token: str
